spring:
  batch:
    initialize-schema: always
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mydbtest?user=root&password=admin&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      database: test
      port: 27017
      host: localhost
