version: "3.5"
services:
  mongocontainer:
    image: mongo
    ports:
       - 27017:27017
    volumes:
       - ./db-notes-mongo:/data/db
  demo:
    image: hw171
    ports:
      - 8080:8080
    depends_on:
      - mongocontainer


