spring:
  data:
    mongodb:
      database: books
      port: 27017
      host: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file: logfile.log
turbine:
  aggregator:
    clusterConfig: SAMPLE-HYSTRIX-AGGREGATE
  appConfig: SAMPLE-HYSTRIX-AGGREGATE